build:
  environment:
    php:
      version: 5.6.20
  tests:
    override:
      - command: 'phpunit --coverage-clover=cover-out'
        coverage:
          file: 'cover-out'
          format: 'php-clover'

tools:
  php_code_sniffer:
    config:
      standard: "PSR2"
